// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY).'
  );
}

// Debug helper: log masked presence of env vars in the browser console to help
// diagnose missing anon key problems. We only log lengths, never the full key.
try {
  const maskedUrl = SUPABASE_URL ? SUPABASE_URL.replace(/(:\/\/)(.*@)?/, '$1***@') : null;
  // mask key length only
  const keyInfo = SUPABASE_PUBLISHABLE_KEY ? `present (len=${SUPABASE_PUBLISHABLE_KEY.length})` : 'missing';
  // eslint-disable-next-line no-console
  console.log('[supabase client] SUPABASE_URL=', maskedUrl, 'PUBLISHABLE_KEY=', keyInfo);
} catch (e) {
  // ignore errors in debug logging
}

// Ensure a single Supabase client across HMR reloads to avoid multiple
// GoTrueClient instances which can cause duplicated listeners and warnings.
declare global {
  interface Window {
    __lumatha_supabase?: ReturnType<typeof createClient>;
  }
}

if (!window.__lumatha_supabase) {
  window.__lumatha_supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export const supabase = window.__lumatha_supabase as ReturnType<typeof createClient>;