// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY).'
  );
}

// Debug helper: log masked presence of env vars in the browser console to help
// diagnose missing anon key problems. We only log lengths, never the full key.
try {
  const maskedUrl = SUPABASE_URL ? SUPABASE_URL.replace(/(:\/\/)(.*@)?/, '$1***@') : null;
  // mask key length only
  const keyInfo = SUPABASE_PUBLISHABLE_KEY ? `present (len=${SUPABASE_PUBLISHABLE_KEY.length})` : 'missing';
  // eslint-disable-next-line no-console
  console.log('[supabase client] SUPABASE_URL=', maskedUrl, 'PUBLISHABLE_KEY=', keyInfo);
} catch (e) {
  // ignore errors in debug logging
}

// Ensure a single Supabase client across HMR reloads to avoid multiple
// GoTrueClient instances which can cause duplicated listeners and warnings.
declare global {
  interface Window {
    __lumatha_supabase?: ReturnType<typeof createClient>;
  }
}

if (!window.__lumatha_supabase) {
  window.__lumatha_supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
  
  // Add error diagnostics for WebSocket/auth failures in production
  try {
    const client = window.__lumatha_supabase;
    const logAuthError = (event: any) => {
      const msg = event?.message || String(event);
      if (msg && (msg.includes('ERR_NAME_NOT_RESOLVED') || msg.includes('net::') || msg.includes('DNS') || msg.includes('auth'))) {
        // Log masked URL and error to help diagnose DNS/auth issues
        const maskedUrl = SUPABASE_URL.replace(/(:\/\/)(.*@)?/, '$1***@');
        console.error('[supabase auth error] URL:', maskedUrl, 'Error:', msg);
      }
    };
    
    // Listen for auth state changes to catch refresh token errors
    const { data: authListener } = client.auth.onAuthStateChange((event, session) => {
      if (event === 'SIGNED_OUT' && !session && localStorage.getItem('supabase.auth.token')) {
        console.warn('[supabase auth] Token exists but session lost - possible refresh failure');
      }
    });
    
    // Cleanup on page unload
    if (authListener?.subscription) {
      window.addEventListener('beforeunload', () => authListener.subscription.unsubscribe());
    }
  } catch (e) {
    console.warn('[supabase diagnostics] Error setting up error listeners:', e);
  }
}

export const supabase = window.__lumatha_supabase as ReturnType<typeof createClient>;